### LOGIN
POST http://localhost:9000/auth/login
Content-Type: application/json

{"email":"name@gmail.com", "password":"plain123"}

### REGISTER
POST http://localhost:9000/auth/register
Content-Type: application/json

{"First_name":"tiyas", "Last_name":"biswas","user_name":"tiyas","email":"tiyas@gmail.com","password":"tiyas123","city":"Tuebingen"}